<?php
$current_page = 'advantages-of-using-bldc-motor-for-micro-and-macro-applications';
$page_title = 'Advantages of using bldc motor for micro and macro applications. – GLOBE SCOTT MOTORS PVT LTD';
$body_class = 'post-template-default single single-post postid-2332 single-format-standard wpb-js-composer js-comp-ver-6.1 vc_responsive';

require_once __DIR__ . '/includes/header.php';
?>

<!-- End of  Header 
    ============================================= -->
<main class="normal-footer">
<!-- breadcrumb -->
<section class="breadcrumb-area breadcrumb-bg image-overlay" style="background-image: url(https://www.globescott.net/wp-content/uploads/2020/02/AdobeStock_115615488_Preview-e1581314210869.jpeg);">
<div class="container">
<div class="row">
<div class="col-12 text-center">
<div class="page-title header1-height">
<h1>Advantages of using bldc motor for micro and macro applications.</h1>
<nav aria-label="breadcrumb">
<ol class="breadcrumb justify-content-center"><li class="breadcrumb-item"><a class="home" href="index/">Home</a></li><li class="breadcrumb-item">Bldcmotor</li><li class="breadcrumb-item active">Advantages of using bldc motor for micro and macro applications.</li></ol> </nav>
</div>
</div>
</div>
</div>
</section>
<!-- breadcrumb-end -->
<!-- blog-section - start
================================================== -->
<section class="blog-area blog-area-pt blog-details pb-70 pt-100">
<div class="container">
<div class="row">
<div class="col-lg-8 blog-post-content">
<div class="blog-wrapper">
<div class="blog-details-content">
<article class="post-2332 post type-post status-publish format-standard has-post-thumbnail hentry category-bldcmotor category-dcmotors category-motors tag-bldc-motor tag-brushless-motor tag-dc-motors tag-motors" id="post-2332">
<img alt="blog img" class="img-fluid full-thumb-img" src="wp-content/uploads/2020/02/blog-image-min.png"/>
<div class="blog-meta-info mb-15">
<ul>
<li><i class="fa fa-user-o"></i>GLOB SCOTT MOTORS</li>
<li><i aria-hidden="true" class="fa fa-clock-o"></i>December 28, 2018</li>
<li class="d-inline-block align-items-center"><i aria-hidden="true" class="fa fa-area-chart"></i>Bldcmotor, DC Motors, Motors</li>
<li><i class="fa fa-comment-o"></i>0 Comments</li>
</ul>
</div>
<div class="blog-inner-blog">
<h5><strong>Background:</strong></h5>
<p>        The industrial revolution was transition from induction motor to the new concept for constant and variable speed application to obtain maximum efficiency over a wide speed range (cost-efficient). All the industries needed more efficient method to attain different speed, this was until the development of PMDC motor. In PMDC motor, stator field is generated by permanent magnet and hence the field remains constant. Due to constant stator field, linear torque/speed characteristics can be obtained.  By simply changing the applied voltage, motor speed can be changed and torque delivered is dependent on current. Since PMDC motor provides high torques, it is widely used in the application where accurate position control is required.</p>
<h5>Introduction to BLDC:</h5>
<p>        BLDC motor provides more advantages than induction motor (AC) and PMDC commutator motor (DC) alone. BLDC motor provides combine benefits of AC and DC motor along with its own unique advantages to application. It combines long life of induction motor and linearity of permanent magnet motor plus its adds own advantages like high speed operating range, high power to low weight ratio (i.e. compact design), improve torque density. Containing features of both AC and DC motors.</p>
<p>        BLDC motor is similar to the synchronous motor; however, the construction varies in comparison. The design consists of housing, winding, permanent magnets and shaft. Core part of BLDC motor is the rotor. Rotor of BLDC motor uses magnet instead of coil winding. For speed control and smooth operation of motor hall sensor or rotor encoder along with controller are used for position sensing of rotor according to the sequential switching of switches are done. Like commutator and brushes in PMDC for mechanical commutation, BLDC uses electronic commutation.</p>
<p>        BLDC motor can be operated by DC source directly using the that provide square wave phase current as excitation, which will produce the back EMF in a trapezoidal form. High speed BLAC motor is also well known as AC Servo motor. Sinusoidal current excitation is used for BLAC motor and back emf produced will be pure sinusoidal in nature. The performance of BLAC or Sine-wave excitation motor is almost similar to the would field induction motor rather than DC commutator motor.</p>
<h5><strong>Classification:</strong></h5>
<p>BLDC motor can be classified based on control strategy and rotor type.</p>
<h6><strong>1) According to control Strategy</strong></h6>
<p>      i) Square wave excitation (BLDC motor)<br/>      ii) Sin-wave excitation (PMSM motor)</p>
<h6><strong>2) According to Rotor Type</strong></h6>
<p>i) Inner Rotor</p>
<ul><li>Surface Permanent Magnet Motor (SPM)</li><li>Inset Permanent Magnet Motor</li><li>Interior Permanent Magnet Motor (IPM)</li></ul>
<p>ii) Outer Rotor.<br/>Comparison of different motors:</p>
<figure class="wp-block-table is-style-stripes"><table class="has-subtle-pale-green-background-color has-background"><thead><tr><th>Sr. No</th><th>Parameter</th><th>DC(Universal)</th><th>Permanent Magnet DC Motor (PMDC)</th><th>AC Induction motor (IM)</th><th>BLDC or Permanent magnet Synchronous Machines (PMSM)</th></tr></thead><tbody><tr><td>1</td><td>Voltage</td><td>AC,DC</td><td>DC</td><td>AC</td><td>AC, DC</td></tr><tr><td>2</td><td>Speed</td><td>8000-20000+</td><td>350-6000</td><td>1200-3400</td><td>2300-3800</td></tr><tr><td>3</td><td>Power</td><td>Very High</td><td>Medium</td><td>Low-Medium</td><td>High</td></tr><tr><td>4</td><td>Efficiency</td><td>60-80</td><td>70-80</td><td>40-90</td><td>70-95</td></tr><tr><td>5</td><td>Life</td><td>Low</td><td>Medium</td><td>Very High</td><td>Very High</td></tr><tr><td>6</td><td>Noise</td><td>Noisy</td><td>Medium</td><td>Quiet</td><td>Very Quiet</td></tr><tr><td>7</td><td>Speed Regulation</td><td>Poor</td><td>Fair</td><td>Good</td><td>Excellent</td></tr><tr><td>8</td><td>Starting Torque</td><td>High</td><td>Very High</td><td>Low-Medium</td><td>Very High</td></tr><tr><td>9</td><td>Reliability</td><td>Less</td><td>Medium</td><td>High</td><td>High</td></tr><tr><td>10</td><td>Controllability &amp; Cost</td><td>Low</td><td>Low-Medium</td><td>Medium</td><td>Medium-High</td></tr><tr><td>11</td><td>Power Density    </td><td>very low</td><td>Low</td><td>Medium</td><td>Very High</td></tr></tbody></table></figure>
<h5>Application:</h5>
<ul><li>Medical – surgical robots, dialysis systems, pressure monitor, lab diagnostics,</li><li>Electronics – feeders, wafer processing, camera crane, telescope control, optics, Nano-testing</li><li>Robotics – humanoid robot, 6-legged robot, service, robotic vehicle, assembly, sewer robots</li><li>Security – video surveillance, mobile inspection, cash dispensers, electromechanical locks</li><li>Instrumentation – precision scales, deep sea sensors, laser leveling, seismometers, measurement</li></ul>
<div class="wp-block-columns are-vertically-aligned-center mr-top">
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:66.66%">
<h3 class="has-text-align-center"><strong>To know more…</strong></h3>
</div>
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:33.33%">
<div class="wp-block-buttons">
<div class="wp-block-button is-style-outline cubutton"><a class="wp-block-button__link has-black-color has-white-background-color has-text-color has-background" href="contact-us/" rel="noreferrer noopener" target="_blank">Contact us</a></div>
</div>
<p></p>
</div>
</div>
<div class="tags-list">
<strong>Tags:</strong> BLDC Motor, brushless motor, DC Motors, Motors </div>
</div>
</article><div class="post-navigation">
<div class="row no-gutters"><div class="col-md-6"><div class="post-previous"> <a class="single-post-nav" href="what-is-bldc-motor/">
<h4 class="post-title">What is bldc motor?</h4>
<h3 class="post-nav-title icon-left"><i class="fa fa-long-arrow-left"></i> Previous Post</h3>
</a>
</div></div><div class="col-md-6"><div class="post-next"> <a class="single-post-nav" href="case-study/">
<h4 class="post-title">Case Study</h4>
<h3 class="post-nav-title icon-right"><i class="fa fa-long-arrow-right"></i> Next Post</h3>
</a>
</div></div></div></div> <div class="no-padding comment-area-page">
<div class="clearfix"></div>
<div class="blog-comment-area col-md-12 p-0">
<div class="nd-post-comment" id="leave-comment">
<div class="comment-respond" id="respond">
<h3 class="comment-title comment-form-title">Leave a Reply <small><a href="advantages-of-using-bldc-motor-for-micro-and-macro-applications.php#respond" id="cancel-comment-reply-link" rel="nofollow" style="display:none;">Cancel Comment</a></small></h3><form action="https://www.globescott.net/wp-comments-post/" class="validate-form formcomment-box" id="add-comment" method="post"><div class="form-group">
<textarea class="form-control rounded-0" cols="30" id="message" name="comment" placeholder="Comment" required="" rows="6"></textarea>
</div><div class="row">
<div class="form-group col-md-6">
<input aria-required="true" class="form-control rounded-0" id="author" name="author" placeholder="Name *" size="30" type="text"/>
</div>
<div class="form-group col-md-6">
<input aria-required="true" class="form-control rounded-0" id="email" name="email" placeholder="Email *" size="30" type="email"/>
</div>
</div>
<div class="form-group">
<input aria-required="true" class="form-control rounded-0" id="website" name="website" placeholder="Website" size="30" type="text"/>
</div>
<p class="comment-form-cookies-consent"><input id="wp-comment-cookies-consent" name="wp-comment-cookies-consent" type="checkbox" value="yes"/> <label for="wp-comment-cookies-consent">Save my name, email, and website in this browser for the next time I comment.</label></p>
<p class="aiowps-captcha"><label for="aiowps-captcha-answer">Please enter an answer in digits:</label></p><div class="aiowps-captcha-equation"><strong>4 × 5 = <input id="aiowps-captcha-string-info" name="aiowps-captcha-string-info" type="hidden" value="vc6jse5uq0"/><input id="aiowps-captcha-temp-string" name="aiowps-captcha-temp-string" type="hidden" value="1784214416"/><input autocomplete="off" id="aiowps-captcha-answer" name="aiowps-captcha-answer" size="2" type="text" value=""/></strong></div><p></p><input class="form-control" name="form_botcheck" type="hidden" value=""/> <button class="btn btn-primary" type="submit">Post Comment</button> <input id="comment_post_ID" name="comment_post_ID" type="hidden" value="2332"/>
<input id="comment_parent" name="comment_parent" type="hidden" value="0"/>
</form> </div><!-- #respond -->
</div><!-- #comments -->
</div>
</div>
</div>
</div>
</div>
<!-- Start Blog Sidebar -->
<!-- End Blog Sidebar -->
<div class="col-lg-4">
<div class="sidebar-blog sidebar-defalt">
<div class="widget mb-30 widget_search" id="search-2"><div class="ws-input"><form action="https://www.globescott.net/" method="get" role="search">
<input name="s" placeholder="Enter Search Keywords" type="search"/>
<button><i class="fa fa-search"></i></button>
</form></div></div>
<div class="widget mb-30 widget_recent_entries" id="recent-posts-2">
<div class="widget-title"><h3>Recent Posts</h3></div>
<ul>
<li>
<a href="case-study/">Case Study</a>
</li>
<li>
<a aria-current="page" href="advantages-of-using-bldc-motor-for-micro-and-macro-applications/">Advantages of using bldc motor for micro and macro applications.</a>
</li>
<li>
<a href="what-is-bldc-motor/">What is bldc motor?</a>
</li>
<li>
<a href="dc-motor-maintenance/">DC motor maintenance.</a>
</li>
<li>
<a href="difference-between-dc-motors-and-geared-motors/">Difference between DC motors and geared motors.</a>
</li>
</ul>
</div><div class="widget mb-30 rounding_rp_widget" id="recent_post_widget-1">
<!-- Footer Blog List
      ========================== -->
<div class="widget-title"><h3>Recent Post</h3></div> <div class="sidebar-rc-post">
<ul>
<li>
<div class="rc-post-thumb">
<a href="case-study/"><img alt="railway case study" class="attachment-rounding-thumb size-rounding-thumb wp-post-image" height="80" loading="lazy" src="wp-content/uploads/2020/07/pexels-darshak-pandya-2526935-100x80.jpg" width="100"/></a>
</div>
<div class="rc-post-content">
<h4><a href="case-study/">Case Study</a></h4>
<span class="widget-date"><i aria-hidden="true" class="fa fa-clock-o"></i> July 27, 2020</span>
</div>
</li>
<li>
<div class="rc-post-thumb">
<a href="advantages-of-using-bldc-motor-for-micro-and-macro-applications/"><img alt="ADVANTAGES OF USING BLDC MOTOR FOR MICRO AND MACRO APPLICATIONS" class="attachment-rounding-thumb size-rounding-thumb wp-post-image" height="80" loading="lazy" src="wp-content/uploads/2020/02/blog-image-min-100x80.png" width="100"/></a>
</div>
<div class="rc-post-content">
<h4><a href="advantages-of-using-bldc-motor-for-micro-and-macro-applications/">Advantages of using bldc motor for micro and macro applications.</a></h4>
<span class="widget-date"><i aria-hidden="true" class="fa fa-clock-o"></i> December 28, 2018</span>
</div>
</li>
<li>
<div class="rc-post-thumb">
<a href="what-is-bldc-motor/"><img alt="WHAT IS BLDC MOTOR" class="attachment-rounding-thumb size-rounding-thumb wp-post-image" height="80" loading="lazy" src="wp-content/uploads/2020/02/blog1-min-1-100x80.png" width="100"/></a>
</div>
<div class="rc-post-content">
<h4><a href="what-is-bldc-motor/">What is bldc motor?</a></h4>
<span class="widget-date"><i aria-hidden="true" class="fa fa-clock-o"></i> October 25, 2018</span>
</div>
</li>
</ul>
</div>
</div> </div>
</div>
</div><!-- row -->
</div><!-- container -->
</section>
<!-- blog-section - End -->
</main>

<?php require_once __DIR__ . '/includes/footer.php'; ?>

